[package]
name = "commitai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caps = "0.5.5"
clap = { version = "4.5.0", features = ["derive"] }
reqwest = "0.11.24"
serde = "1.0.196"
tokio = "1.36.0"
